name: 'Deploy Vuepress to GitHub Pages with CNAME'
description: 'This action will handle the building and deploying process Vuepress to GitHub Pages.'
author: 'rreichel3'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'orange'
